version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres # This is the default database name
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-stream-pro
    environment:
      - PORT=${PORT}
    ports:
      - '3333:3333'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: data-stream-pro-db
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db
